name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        # run all tests but skip any containing "v6" since github actions host is using IPv4 only
      - name: Run tests
        run: cargo test --verbose -- --skip v6
